Closes #109
opengeospatial/ets-ogcapi-edr10 pull request #127
Opened 2024-05-24 11:00 UTC by bpross-52n

Closes #109

2024-05-27 07:51 UTC, dstenger requested changes
@bpross-52n Code looks good so far.

However, a unit test is failing:
```
...
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.239 sec <<< FAILURE! - in org.opengis.cite.ogcapiedr10.VerifyTestNGController
testValidateTestRunArgs(org.opengis.cite.ogcapiedr10.VerifyTestNGController)  Time elapsed: 1.239 sec  <<< ERROR!
java.lang.NullPointerException: null lexical form for literal
	at org.opengis.cite.ogcapiedr10.VerifyTestNGController.testValidateTestRunArgs(VerifyTestNGController.java:30)


Results :

Tests in error: 
  VerifyTestNGController.testValidateTestRunArgs:30 » NullPointer null lexical f...

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
```

Can you please check this?

2024-05-27 12:58 UTC, dstenger requested changes
I tested the changes with
* https://demo.pygeoapi.io/master
* https://demo.pygeoapi.io/master/openapi

Result with this feature branch:
![Bildschirmfoto vom 2024-05-27 14-57-27](https://github.com/opengeospatial/ets-ogcapi-edr10/assets/2989166/9de8f3b7-7843-43b4-b591-29fab9397bbe)

The behavior with current master branch:
![Bildschirmfoto vom 2024-05-27 14-57-04](https://github.com/opengeospatial/ets-ogcapi-edr10/assets/2989166/5e4589c4-6f54-4007-91a7-e545c6d8dfe1)

This is not expected. @bpross-52n Can you please check why there is a difference?

2024-05-28 06:31 UTC, bpross-52n commented
@dstenger I used a wrong method to obtain the API description as String. With [0a34024](https://github.com/opengeospatial/ets-ogcapi-edr10/pull/127/commits/0a34024e7aee6caa0016b275242d2726ea6cb172), the results should be the same again.

2024-05-28 08:42 UTC, dstenger approved these changes

2024-05-28 08:43 UTC, merged